books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from books import views
app_name = 'books'
urlpatterns = [

    path('', views.index.as_view(), name='index'),
    path('about/', views.about, name="about"),
    path('detail/<int:id>', views.detail.as_view(), name='detail'),
    path('categories/<janr>', views.categories.as_view(), name='categories'),
    path('<int:fav_id>/favourite_post/',
         views.favourite_post, name='favourite_post'),

    path('favourites/', views.favorite_list, name='favorite_list')



]

root/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from books import views
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('user', include('user.urls')),
    path('', include('books.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

'''
urlpatterns = [

    path('admin/', admin.site.urls), ]

urlpatterns += i18n_patterns(

    path('user', include('user.urls')),
    path('', include('books.urls')),
    prefix_default_language=False
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
'''

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='user'

urlpatterns=[
    path('login/',views.loginUser,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logoutUser,name='logout')

]

books/models.py
from django.db import models
from django.conf import settings
from ckeditor.fields import RichTextField
import datetime
from django.contrib.auth.models import User

# Create your models here.
options3 = [
    ('dedektiv', 'Dedektiv'),
    ('fantastik', 'Fantastik'),
    ('psixoloji', 'Psixoloji'),
    ('huquq', 'Hüquq'),
    ('roman', 'Roman'),
    ('dunya_edebiyyati', 'Dünya ədəbiyyatı'),
    ('felsefe', 'Fəlsəfə'),
]


class Kitablar(models.Model):
    Ad = models.CharField(max_length=70, verbose_name='Ad')
    Mezmun = RichTextField(default="", verbose_name='Məzmun')
    Yazar = models.CharField(max_length=25, default="", verbose_name='Yazar')
    Qiymet = models.CharField(max_length=8, default='', verbose_name='Qiymət')
    shekil = models.ImageField(verbose_name='Şəkil', default='')
    tarix = models.DateTimeField(
        auto_now_add=True, verbose_name="Əlavə edildiyi tarix")
    janr = models.CharField(max_length=20, choices=options3,
                            )
    options1 = (('Mövcud', 'mövcud'),
                ('Mövcud deyil', 'mövcud deyil'))

    options2 = (('Yeni', 'yeni'),
                ('İşlənmiş', 'işlənmiş'))

    options4 = (('Azərbaycan', 'Azərbaycan'),
                ('Türkçe', 'Türkçe'),
                ('Руский ', 'Руский '),
                ('English', 'English'))
    icare_ucun = models.CharField(
        max_length=20, choices=options1, verbose_name='Kirayə üçün mövcudluğu')
    veziyyet = models.CharField(
        max_length=20, choices=options2, verbose_name='Vəziyyəti', default='')

    dil = models.CharField(max_length=100, choices=options4,
                           verbose_name='Dil', default='')

    favourite = models.ManyToManyField(
        User, related_name='favourite', blank=True)

    def __str__(self):
        return self.Ad

    class Meta:
        verbose_name_plural = 'Kitablar'
        ordering = ['tarix']

templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  {% block about_page %}
  
  {% endblock about_page %}
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}


<body>
<div class="mt-5 pt-4">
{% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
  {% endfor %}
{% endif %}
</div>
    {% block content %}
    {% endblock content %}
    
 

    {% include "footer.html" %}
    {% include "scripts.html" %}
</body>
</html>

templates/categories.html
{% extends "base.html" %}
  {% block content %}

  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">
    
    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://www.wallpaperflare.com/static/87/362/502/books-stack-book-store-stack-of-books-wallpaper.jpg'); background-repeat: no-repeat; background-size: cover;background-attachment: fixed;   background-position: center center;
        background-size: 1000px 1000px
">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
                        {% for item in object_list|slice:":1"  %}

<h1 class="mb-4"><h1 style=" font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;color:darkslategrey; font-size: 80px;text-shadow: 0 1px 0 #ccc,
0 2px 0 #c9c9c9,
0 3px 0 #bbb,
0 4px 0 #b9b9b9,
0 5px 0 #aaa,
0 6px 1px rgba(0,0,0,.1),
0 0 5px rgba(0,0,0,.1),
0 1px 3px rgba(0,0,0,.3),
0 3px 5px rgba(0,0,0,.2),
0 5px 10px rgba(0,0,0,.25),
0 10px 10px rgba(0,0,0,.2),
0 20px 20px rgba(0,0,0,.15);
color:#955251"><strong>{{ item.get_janr_display }}</strong> janrında Kitablar</h1></header><br>
                
              </h1>

              {% endfor %}
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      
    </div>
    <!--/.Slides-->


  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar--><!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5 ">
      <ul class="navbar-nav mr-auto">
     <li class="nav-item active">
     {% for item in object_list|slice:":1"  %}
              <a class="nav-link" href={% url 'books:categories' item.janr %}>{{ item.get_janr_display }}</a>
            </li>
       {% endfor %} 
         </ul>
        
        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
     {% for item in janrlar %}
         <li class="nav-item">
              <a class="nav-link" href={% url 'books:categories' item.0 %}>{{item.1}}</a>
            </li>
        {% endfor %}
        </ul>
          <!-- Links -->
          {% block search %}
  <form class="form-inline my-2 my-lg-0" method='GET'>
    {% csrf_token %}
    <div class="form-group">
        <select class="form-control" name='dil'>
          <option disabled selected>Dili seçin</option>
          <option>Azərbaycan</option>
          <option>Türkçe</option>
          <option>Руский</option>
          <option>English</option>
        </select>
      </div>
  <input class="form-control mr-sm-2" name='keyword' type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-blue-grey my-2 my-sm-0 " type="submit">Search</button>
</form>
          {% endblock search %}
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->      


        <!--Grid row-->
           <div class='container-fluid' id='section02'>
    <div class="row">

      {% for item in object_list  %}
      <div class="col-md-3 ">

          <div class="card" style='max-height:90%'>

  <!-- Card image -->
  <div class="view overlay">
    <a href="{% url 'books:detail' item.id %}"> 
    <img class="card-img-top" style='width: 100%; height: 15vw; object-fit: cover;
   z-index: 9999;' src="/media/{{ item.shekil }}"  
      alt="Card image cap"></a>
    <a>
      <div class="mask rgba-white-slight"></div>
    </a>
  </div>

  <!-- Card content -->
  <div class="card-body white-color black-text rounded-bottom">


    <!-- Title -->
   <a href='{% url 'books:detail' item.id %}'>  <h5 class="card-title text-center" style='color:red'><strong>{{ item.Ad }}</strong></h5>
    <hr class="hr-dark"></a>
    <!-- Text -->
    
    </h1 class="card-text black-text"> Yazar: {{ item.Yazar }}</h1>
 
    <p class="card-text black-text">Janr: {{ item.get_janr_display }}</p>
<a href='{% url 'books:detail' item.id %}'> <h2><p class="font-weight-bold text-center text-warning">{{item.Qiymet}} ₼</p></h2></a>


    <!-- Link -->


  </div>

</div>
        </div>
      {% endfor %}
    </div>
  </div>   

    </div>
  </main>
  <!--Main layout-->
  {% endblock content %}

  
{% include "footer.html" %}

</body>

</html>

templates/detail.html
{% extends "base.html" %}
{% block content %}


  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="/media/{{ data.shekil }}" class="img-fluid" style="width: 60%; height: 23vw; object-fit: fill;" alt="">
        
        </div>
        <!--Grid column-->
       <div class="col-md-5 mb-4">
      <h1  style='margin-right:50px%; color:brown'><strong>{{data.Ad}}</strong></h1><br>
      <h3> Janr: <a href="{% url 'books:categories' data.janr %}"><span class="badge purple mr-1">{{data.janr}}</span></h3></a><br>
      <h4> Yazar: {{data.Yazar}}</h4><br>
      <h4> Vəziyyəti: {{data.veziyyet}}</h4><br>
      <h4> Kirayə üçün: {{data.icare_ucun}}</h4> <br>     
      <h1><p class="font-weight-bold text-left text-warning">{{data.Qiymet}} ₼</p></h1>
      <form method='POST' class="d-flex justify-content-left" 
            action= {% if user.is_authenticated %}
            "{% url 'books:favourite_post' data.id %}"
              {% else %}
            "{% url 'user:login' %}"
              {% endif %}>
            {% csrf_token %}
              <button class="btn btn-primary btn-md my-0 p" type="submit" value="{{data.id}}">
              {% if is_favorite %}
              Sevimlilərdən kənarlaşdır
              {% else %}
              Sevimlilərə əlavə et
              {% endif %}
              </button>
            </form>
       </div>
        <!--Grid column-->
        <div class="col-md-20 mb-4">

          <!--Content-->
          <div class="p-4">



            <h1 class="font-weight-bold">Məzmun</h1>

            <p>{{data.Mezmun|safe}}</p>

            
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">
      <h3 class="my-4 h4">Tövsiyyə olunan kitablar</h3><br>
</div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">
{% for item in random_books  %}
        <div class="col-lg-4 col-md-6 mb-4">

          <a href="{% url 'books:detail' item.id %}">
          <img src="/media/{{ item.shekil }}" cclass="card-img-top" style="width: 87%; height: 23vw; object-fit: fill;" alt=""></a>

        </div>
{% endfor %}
        <!--Grid column-->

        <!--Grid column-->


      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/favourites.html
{% extends "base.html" %}
  {% block content %}

  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://www.wallpaperflare.com/static/87/362/502/books-stack-book-store-stack-of-books-wallpaper.jpg'); background-repeat: no-repeat; background-size: cover;background-attachment: fixed;   background-position: center center;
        background-size: 1000px 1000px
">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
                <strong>
   <h1 style="text-shadow: 0 2px 0 #ccc,
        0 2px 0 #c9c9c9,
        0 3px 0 #bbb,
        0 4px 0 #b9b9b9,
        0 5px 0 #aaa,
        0 6px 1px rgba(0,0,0,.1),
        0 0 5px rgba(0,0,0,.1),
        0 1px 3px rgba(0,0,0,.3),
        0 3px 5px rgba(0,0,0,.2),
        0 5px 10px rgba(0,0,0,.25),
        0 10px 10px rgba(0,0,0,.2),
        0 20px 20px rgba(0,0,0,.15);
        color:green;
        font-size: 100px;
        ">Sevimli Kitablarınız</h1>
                </strong>

              <p>
                <h4><strong>Kitabların kirayəsi</strong> <i class="fas fa-book "></i></h4>
              </p>
              </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar--><!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5" style='width:43%;'>

        <!-- Navbar brand -->


        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          {% block search %}
  <form class="form-inline my-2 my-lg-0" method='GET'>
    {% csrf_token %}
    <div class="form-group">
        <select class="form-control" name='dil'>
          <option disabled selected>Dili seçin</option>
          <option>Azərbaycan</option>
          <option>Türkçe</option>
          <option>Руский</option>
          <option>English</option>
        </select>
      </div>
  <input class="form-control mr-sm-2" name='keyword' type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
          {% endblock search %}
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->      


        <!--Grid row-->
           <div class='container-fluid' id='section02'>
    <div class="row">

      {% for item in favorite_posts  %}
      <div class="col-md-3 ">

          <div class="card" style='max-height:90%'>

  <!-- Card image -->
  <div class="view overlay">
    <a href='{% url 'books:detail' item.id %}'> 
    <img class="card-img-top" style='width: 100%; height: 15vw; object-fit: cover;
   z-index: 9999;' src="/media/{{ item.shekil }}"  
      alt="Card image cap"></a>
    <a>
      <div class="mask rgba-white-slight"></div>
    </a>
  </div>

  <!-- Card content -->
  <div class="card-body white-color black-text rounded-bottom">


    <!-- Title -->
   <a href='{% url 'books:detail' item.id %}'  <h5 class="card-title text-center" style='color:red'><strong>{{ item.Ad }}</strong></h5>
    <hr class="hr-dark"></a>
    <!-- Text -->
    
    </h1 class="card-text black-text"> Yazar: {{ item.Yazar }}</h1>
 
    <p class="card-text black-text">Janr: {{ item.get_janr_display }}</p>
<a href='{% url 'books:detail' item.id %}'> <h2><p class="font-weight-bold text-center text-warning">{{item.Qiymet}} ₼</p></h2></a>


    <!-- Link -->


  </div>

</div>
        </div>
      {% endfor %}
    </div>
  </div>   

    </div>
  </main>
  <!--Main layout-->
  {% endblock content %}

  
{% include "footer.html" %}

</body>

</html>

templates/index.html
{% extends "base.html" %}
  {% block content %}

  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://www.wallpaperflare.com/static/87/362/502/books-stack-book-store-stack-of-books-wallpaper.jpg'); background-repeat: no-repeat; background-size: cover;background-attachment: fixed;   background-position: center center;
        background-size: 1000px 1000px
">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
                <strong>
   <h1 style="text-shadow: 0 2px 0 #ccc,
        0 2px 0 #c9c9c9,
        0 3px 0 #bbb,
        0 4px 0 #b9b9b9,
        0 5px 0 #aaa,
        0 6px 1px rgba(0,0,0,.1),
        0 0 5px rgba(0,0,0,.1),
        0 1px 3px rgba(0,0,0,.3),
        0 3px 5px rgba(0,0,0,.2),
        0 5px 10px rgba(0,0,0,.25),
        0 10px 10px rgba(0,0,0,.2),
        0 20px 20px rgba(0,0,0,.15);
        color:green;
        font-size: 100px;
        ">Novella Kitab Evi</h1>
                </strong>

              <p>
                <h4><strong>Kitabların kirayəsi</strong> <i class="fas fa-book "></i></h4>
              </p>
              </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar--><!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5" style='width:105%;'>

        <!-- Navbar brand -->
        <span class="navbar-brand">Kateqoriyalar:</span>


        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
        {% for item in data|slice:':7' %}
         <li class="nav-item">
<a class="nav-link" href={% url 'books:categories' item.janr %}>{{ item.get_janr_display }}</a>
            </li>
        {% endfor %}

          </ul>
          <!-- Links -->
          {% block search %}
  <form class="form-inline my-2 my-lg-0" method='GET'>
    {% csrf_token %}
    <div class="form-group">
        <select class="form-control" name='dil'>
          <option disabled selected>Dili seçin</option>
          <option>Azərbaycan</option>
          <option>Türkçe</option>
          <option>Руский</option>
          <option>English</option>
        </select>
      </div>
  <input class="form-control mr-sm-2" name='keyword' type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
          {% endblock search %}
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->      


        <!--Grid row-->
           <div class='container-fluid' id='section02'>
    <div class="row">

      {% for item in data  %}
      <div class="col-md-3 ">

          <div class="card" style='max-height:90%'>

  <!-- Card image -->
  <div class="view overlay">
    <a href='{% url 'books:detail' item.id %}'> 
    <img class="card-img-top" style='width: 100%; height: 15vw; object-fit: cover;
   z-index: 9999;' src="/media/{{ item.shekil }}"  
      alt="Card image cap"></a>
    <a>
      <div class="mask rgba-white-slight"></div>
    </a>
  </div>

  <!-- Card content -->
  <div class="card-body white-color black-text rounded-bottom">


    <!-- Title -->
   <a href='{% url 'books:detail' item.id %}'>  <h5 class="card-title text-center" style='color:red'><strong>{{ item.Ad }}</strong></h5>
    <hr class="hr-dark"></a>
    <!-- Text -->
    
    </h1 class="card-text black-text"> Yazar: {{ item.Yazar }}</h1>
 
    <p class="card-text black-text">Janr: {{ item.get_janr_display }}</p>
<a href='{% url 'books:detail' item.id %}'> <h2><p class="font-weight-bold text-center text-warning">{{item.Qiymet}} ₼</p></h2></a>


    <!-- Link -->


  </div>

</div>
        </div>
      {% endfor %}
    </div>
  </div>   

    </div>
  </main>
  <!--Main layout-->
  {% endblock content %}

  
{% include "footer.html" %}

</body>

</html>

templates/login.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-4 offset-md-3">
    <h3>Hesabınıza daxil olun</h3>
    <hr>
    <form method="POST">
      {% csrf_token %}
      {{form|crispy}}
      {% if messages %}
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
      {% endif %}
      <br>
      <button type='submit' class='btn btn-danger'>Təsdiqləyin</button>
        <hr>
        <a href = "{% url 'user:register' %}"><p>Hesabınız yoxdursa buradan qeydiyyatdan keçin</p></a>

  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock content %}

templates/navbar.html
<!-- Navbar -->
{% load static i18n %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar" style='
    z-index: 9999;'>
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="/">
            <strong class="blue-text">Novella</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="/about" target="_blank">Haqqımızda</a>
                </li>

            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">

                {% if request.user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'books:favorite_list' %}">
                        <i class="fas fa-heart"></i>
                        <span class="clearfix d-none d-sm-inline-block"> Sevimlilər </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="#">
                        <i class='fas fa-user-circle'></i>
                        <span class="clearfix d-none d-sm-inline-block"> {{user}} </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'user:logout' %}">
                        <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                    </a>
                </li>
                {% else %}

                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'user:login' %}">
                        <span class="clearfix d-none d-sm-inline-block"> Login </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'user:register' %}">
                        <span class="clearfix d-none d-sm-inline-block"> Signup </span>
                    </a>
                </li>

                {% endif %}
                <li class="nav-item">
                    <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                        <input type="hidden" name='next' value='{{ redirect_to }}'>
                        <select name="language" id="" class="form-control form-control-sm">
                        
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}

                        {% for language in languages %}

                        <option type='submit' value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                             {{ language.name_local }} ({{ language.code }})
                        </option>
              {% endfor %}
            </select>
                        <input type="submit" value="Go">
                    </form>
                </li>
            </ul>

        </div>

    </div>
</nav>
<!-- Navbar -->

templates/register.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-4 offset-md-3">
    <h3>Hesabınıza daxil olun</h3>
    <hr>
    <form method="POST">
      {% csrf_token %}
      {{form|crispy}}
      {% if messages %}
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
      {% endif %}
      <br>
      <button type='submit' class='btn btn-danger'>Təsdiqləyin</button>



  </div>
</div>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}